version: "3.9"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.api
    container_name: medoptix_api
    ports:
      - "8000:8000"
    env_file:
      - ../.env

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile.ui
    container_name: medoptix_ui
    ports:
      - "8501:8501"
    depends_on:
      - api
    environment:
      - API_URL=http://api:8000/predict
